config/routes.rb
Video::Application.routes.draw do
  resources :clips

  resources :questions

  resources :categories

  resources :channels

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => "users#new"

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :name
  has_many :clips
  
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  before_filter :login_required

  def index
    @channels = Channel.all
  end

  def show
    @channel = Channel.find(params[:id])
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(params[:channel])
    if @channel.save
      redirect_to @channel, :notice => "Successfully created channel."
    else
      render :action => 'new'
    end
  end

  def edit
    @channel = Channel.find(params[:id])
  end

  def update
    @channel = Channel.find(params[:id])
    if @channel.update_attributes(params[:channel])
      redirect_to @channel, :notice  => "Successfully updated channel."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy
    redirect_to channels_url, :notice => "Successfully destroyed channel."
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_form.html.erb
<%= form_for @channel do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/channels/edit.html.erb
<% title "Edit Channel" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @channel %> |
  <%= link_to "View All", channels_path %>
</p>

app/views/channels/index.html.erb
<% title "Channels" %>

<table>
  <tr>
    <th>Name</th>
  </tr>
  <% for channel in @channels %>
    <tr>
      <td><%= channel.name %></td>
      <td><%= link_to "Show", channel %></td>
      <td><%= link_to "Edit", edit_channel_path(channel) %></td>
      <td><%= link_to "Destroy", channel, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Channel", new_channel_path %></p>

app/views/channels/new.html.erb
<% title "New Channel" %>

<%= render 'form' %>

<p><%= link_to "Back to List", channels_path %></p>

app/views/channels/show.html.erb
<% title "Channel" %>

<p>
  <strong>Name:</strong>
  <%= @channel.name %>
</p>

<p>
 <% if can? :update || :destroy, @channel%>
  	<%= link_to "Edit", edit_channel_path(@channel) %> |
  	<%= link_to "Destroy", @channel, :confirm => 'Are you sure?', :method => :delete %> |
 <% end %>
  <%= link_to "View All", channels_path %>
</p>