config/routes.rb
Video::Application.routes.draw do
  resources :clips

  resources :questions

  resources :categories

  resources :channels

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  root :to => "users#new"

end

app/models/clip.rb
class Clip < ActiveRecord::Base
  attr_accessible :title, :description, :clip_file_name, :clip_content_type, :clip_file_size, :clip_update_at, :live, :category_id, :channel_id, :user_id, :position
  belongs_to :category
  belongs_to :channel
  has_many :questions, :dependent => :destroy
  belongs_to :user

  has_many :your_queues
  has_many :your_queues, :through => :users

  validates :title, :description, :presence => true

end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  before_filter :login_required

  def index
    @clips = Clip.all
  end

  def show
    @clip = Clip.find(params[:id])
  end

  def new
    @clip = Clip.new
    @clip.user_id = current_user.id
  end

  def create
    @clip = Clip.new(params[:clip])
    if @clip.save
      redirect_to @clip, :notice => "Successfully created clip."
    else
      render :action => 'new'
    end
  end

  def edit
    @clip = Clip.find(params[:id])
  end

  def update
    @clip = Clip.find(params[:id])
    if @clip.update_attributes(params[:clip])
      redirect_to @clip, :notice  => "Successfully updated clip."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @clip = Clip.find(params[:id])
    @clip.destroy
    redirect_to clips_url, :notice => "Successfully destroyed clip."
  end
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/_form.html.erb
<%= form_for @clip do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :clip_file_name %><br />
    <%= f.text_field :clip_file_name %>
  </p>
  <p>
    <%= f.label :clip_content_type %><br />
    <%= f.text_field :clip_content_type %>
  </p>
  <p>
    <%= f.label :clip_file_size %><br />
    <%= f.text_field :clip_file_size %>
  </p>
  <p>
    <%= f.label :clip_update_at %><br />
    <%= f.datetime_select :clip_update_at %>
  </p>
  <p>
    <%= f.label :live %><br />
    <%= f.check_box :live %>
  </p>
  <p>
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.find(:all), :id, :name%>
  </p>
  <p>
    <%= f.label :channel_id %><br />
    <%= f.collection_select :channel_id, Channel.find(:all), :id, :name%>
  </p>
  <p>
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </p>
  <p><%= f.hidden_field :user_id %>
    <%= f.submit %>
  </p>
<% end %>

app/views/clips/edit.html.erb
<% title "Edit Clip" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @clip %> |
  <%= link_to "View All", clips_path %>
</p>

app/views/clips/index.html.erb
<% title "Clips" %>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Clip File Name</th>
    <th>Clip Content Type</th>
    <th>Clip File Size</th>
    <th>Clip Update At</th>
    <th>Live</th>
    <th>Category</th>
    <th>Channel</th>
    <th>User</th>
    <th>Position</th>
  </tr>
  <% for clip in @clips %>
    <tr>
      <td><%= clip.title %></td>
      <td><%= clip.description %></td>
      <td><%= clip.clip_file_name %></td>
      <td><%= clip.clip_content_type %></td>
      <td><%= clip.clip_file_size %></td>
      <td><%= clip.clip_update_at %></td>
      <td><%= clip.live %></td>
      <td><%= clip.category_id %></td>
      <td><%= clip.channel_id %></td>
      <td><%= clip.user_id %></td>
      <td><%= clip.position %></td> 
      <td><%= link_to "Show", clip %></td>
      <% if can? :update, @clip %>
      <td><%= link_to "Edit", edit_clip_path(clip) %></td>
      <%end%>
      <% if can? :destroy, @clip%>
      <td><%= link_to "Destroy", clip, :confirm => 'Are you sure?', :method => :delete %></td>
      <%end%>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Clip", new_clip_path %></p>

app/views/clips/new.html.erb
<% title "New Clip" %>

<%= render 'form' %>

<p><%= link_to "Back to List", clips_path %></p>

app/views/clips/show.html.erb
<% title "Clip" %>

<p>
  <strong>Title:</strong>
  <%= @clip.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @clip.description %>
</p>
<p>
  <strong>Clip File Name:</strong>
  <%= @clip.clip_file_name %>
</p>
<p>
  <strong>Clip Content Type:</strong>
  <%= @clip.clip_content_type %>
</p>
<p>
  <strong>Clip File Size:</strong>
  <%= @clip.clip_file_size %>
</p>
<p>
  <strong>Clip Update At:</strong>
  <%= @clip.clip_update_at %>
</p>
<p>
  <strong>Live:</strong>
  <%= @clip.live %>
</p>
<p>
  <strong>Category:</strong>
  <%= @clip.category_id %>
</p>
<p>
  <strong>Channel:</strong>
  <%= @clip.channel_id %>
</p>
<p>
  <strong>User:</strong>
  <%= @clip.user_id %>
</p>
<p>
  <strong>Position:</strong>
  <%= @clip.position %>
</p>

<p>
  <%= link_to "Edit", edit_clip_path(@clip) %> |
  <%= link_to "Destroy", @clip, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", clips_path %>
</p>